// <auto-generated />
// This file is generated by AstGenerator. Do not edit it manually.
using LoxInterpreter.Parser;
using LoxInterpreter;
public class Grouping:Expr
{
    public Expr Expression { get; init; }
    public override T Accept<T>(IVisitor<T> visitor)
    {
        return visitor.VisitGrouping(this);
    }
}
