// <auto-generated />
// This file is generated by AstGenerator. Do not edit it manually.
using LoxInterpreter.Parser;
namespace LoxInterpreter;
public interface IVisitor<T>
{
   public T VisitBinary(Binary binary);
   public T VisitGrouping(Grouping grouping);
   public T VisitLiteral(Literal literal);
   public T VisitUnary(Unary unary);
}
