// <auto-generated />
// This file is generated by AstGenerator. Do not edit it manually.
using LoxInterpreter.Parser;
using LoxInterpreter;
public class Unary:Expr
{
    public Token Op { get; init; }
    public Expr Right { get; init; }
    public override T Accept<T>(IVisitor<T> visitor)
    {
        return visitor.VisitUnary(this);
    }
}
